version: '3.8'

services:
  telegram_bot:
    build: .
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3